# skip this
name: events advance types vs
on: 
  pull_request:
    types: ['opened']
    branches: ['main']
  push:
    branches: ['main']
    paths: ['**.yml']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: use node
        uses: actions/setup-node@v6
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build
      - name: deploy app
        run: echo "deploying app.."  
