name: lint checker
on: [push]
jobs:
  run-lint:
      runs-on: ubuntu-latest
      steps:
        - name: get code
          uses: actions/checkout@v6
        - name: use node
          uses: actions/setup-node@v6
          with: 
            node-version: 22
        - name: install dependencies
          run: npm ci
        - name: run lint
          run: npm run lint
  run-tests:
      needs: run-lint
      runs-on: ubuntu-latest
      steps:
        - name: get code
          uses: actions/checkout@v6
        - name: use node
          uses: actions/setup-node@v6
          with: 
            node-version: 22
        - name: install dependencies
          run: npm ci
        - name: run tests
          run: npm run test -- --watch=false --browsers=ChromeHeadless
  run-build:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v6
      - name: use node
        uses: actions/setup-node@v6
        with: 
          node-version: 22
      - name: install dependencies
        run: npm ci
      - name: run build
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: |
            dist
            package.json
      - name: deeploy app
        run: echo "deploying..."
  run-deploy:
    needs: run-build
    runs-on: ubuntu-latest
    steps:
     - name: download artifacts
       uses: actions/download-artifact@v7
       with:
          name: dist-files
     - name: verify artifacts
       run: ls